### ISSUE TITLE
Overrides not really working

### ISSUE THREAD

**Issue by Pszek** [sindresorhus/xo#82] opened 2016-02-17 13:47 UTC
I tried to use 'overrides' in order to apply different linter rules for some testing scripts.:

```json
 "xo": {  
    "esnext": true,
	"semicolon": false,
	"overrides": [{
  	  "files": "test/*.js",
  	  "globals": [
  		"casper"
  	  ],
  	  "rules": {
  		"no-undef": true,
  		"prefer-arrow-callback": false
  	  }
         }],
```

Unfortunately it didn't work, but resolved it by using this in each script file:
```javascript
/* global casper */
/* eslint prefer-arrow-callback:0 */`

**Comment by sindresorhus** [comment] 2016-02-17 13:48
Duplicate of https://github.com/sindresorhus/xo/issues/78.

**Closed by sindresorhus** 2016-02-17 13:48 UTC
