### ISSUE TITLE
Unexpected token t

### ISSUE THREAD

**Issue by dawsonbotsford** [sindresorhus/xo#116] opened 2016-05-14 05:19 UTC
async operations are suddenly failing that were previously not. Even my Travis builds are failing. Here is the line which fails (taken directly from [del](https://github.com/sindresorhus/del)):

 ```js
test('delete files - async', async t => {
```

To reproduce, I made my own coding an externality by downloading and running the tests for `del`.

```shell
$ git clone git@github.com:sindresorhus/del.git
$ npm install
$ npm test

  test.js:29:36
  ✖  29:36  Parsing error: Unexpected token t

  1 error
```

[sist](https://github.com/dawsonbotsford/sist) output:

### OS
Darwin  
x64  

### node  
`npm -v`: 3.8.6
`node --version`: v5.11.0

### shell  
`uname`: Darwin
`echo $SHELL`: /bin/zsh
`echo $TERM`: xterm-256color
`echo $TERM_PROGRAM`: iTerm.app

Time created: Fri May 13 2016 22:16:05 GMT-0700 (PDT)

**Comment by jamestalmage** [comment] 2016-05-14 06:13
This is caused by https://github.com/eslint/eslint/issues/6158.
There is already an open PR to fix the issue: https://github.com/eslint/eslint/pull/6160

Pin eslint to 2.9 until that is resolved. You can do that in `package.json`. Here is the updated `package.json` that makes the `del` example work.

```js
  "devDependencies": {
   ...
    "xo": {
      "version": "*",
      "dependencies" : {
        "eslint": "2.9.x"
      }
    }
  }
```

@sindresorhus

**Comment by sindresorhus** [comment] 2016-05-14 09:36
Pinned in 0.15.1.

**Comment by kevva** [comment] 2016-05-15 19:46
Should be fixed in `2.10.1`.

**Comment by sindresorhus** [comment] 2016-05-15 19:48
Yup, I'm just giving it some days in case it there were other bugs.

**Comment by ntwb** [comment] 2016-06-16 00:04
This can be closed now, ESLint was _unpinned_ in https://github.com/sindresorhus/xo/commit/4ae7f091b1c1d35d405c8d2ad53d0806da4f24d2

**Closed** 2016-06-16 03:52 UTC
