### ISSUE TITLE
Passing settings for eslint-plugin-import

### ISSUE THREAD

**Issue by EJIqpEP** [sindresorhus/xo#139] opened 2016-08-15 12:59 UTC
Hello guys. You did really nice project! But I can't get from documentation how to change settings for eslint-plugin-import.
I need to add import/external-module-folders folder to settings so my custom folder for webpack is resolved.
Is it possible?

**Comment by sindresorhus** [comment] 2016-08-15 14:47
Duplicate of #138.

**Closed by sindresorhus** 2016-08-15 14:47 UTC
