### ISSUE TITLE
Output concealed.

### ISSUE THREAD

**Issue by P-Seebauer** [sindresorhus/xo#253] opened 2017-09-17 14:53 UTC
When I start `xo` with the standard config, all ouput, except the first filenames is concealed (ANSI-Code 8m).

I'm running it on Ubuntu 16.04, ubuntu-terminal (don't know what it is called, the ubuntu variant of gnome-terminal), inside `tmux` (does not show if not in tmux, but the command is there anyway).

I tested it on the master branch for node versions 4, 6 and 8.

[Here](https://github.com/sindresorhus/xo/files/1309148/typescript.txt) is a [script](https://linux.die.net/man/1/script) [output](https://github.com/sindresorhus/xo/files/1309148/typescript.txt) from a run on `node` 8. Note the `\x1b[8m` after the filename (and the underline-end command) that never gets reset.

I don't know if this just because of `tmux` supporting `\e[8m` some strange termcap settings, or if this just never came up, because *conceal* isn't widely supported.

And the output then looks like this: 
Without selection(pretty useless, but just to get my point across, that I barely can use `xo` that way)
![grafik](https://user-images.githubusercontent.com/502407/30521905-dc86f2d0-9bc7-11e7-9523-4d0739784712.png)

With Selection (also pretty useless, just to give an impression how conceal works here):
![grafik](https://user-images.githubusercontent.com/502407/30521909-ebe6fbb2-9bc7-11e7-8b2f-0c0ec2f92d7f.png)

**Comment by kevva** [comment] 2017-09-18 19:20
Duplicate of https://github.com/chalk/chalk/issues/131.

**Closed by kevva** 2017-09-18 19:20 UTC

**Comment by P-Seebauer** [comment] 2017-09-19 11:26
Sorry, thanks, will look upstream.
