### ISSUE TITLE
Can't keep configuration from remote repo

### ISSUE THREAD

**Issue by YerkoPalma** [sindresorhus/xo#107] opened 2016-04-22 12:39 UTC
### Versions

```
npm = 3.8.7
xo = 0.14.0
eslint = 2.8.0
```

I lost my `xo` config when cloning a project in a cloud IDE.

This is what happened. I successfully added xo to an existing project and all worked fine, then I commit my changes to github. Now, I pulled that project from github in cloud9 (cloud IDE with Ubuntu installed) and when I run the `xo` command I get 

```
Error: Failed to load plugin no-empty-blocks: Cannot find module 'eslint-plugin-no-empty-blocks'
Referenced from: 
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.module.exports.load (/home/ubuntu/workspace/node_modules/eslint/lib/config/plugins.js:116:26)
    at Array.forEach (native)
    at Object.module.exports.loadAll (/home/ubuntu/workspace/node_modules/eslint/lib/config/plugins.js:138:21)
    at load (/home/ubuntu/workspace/node_modules/eslint/lib/config/config-file.js:502:21)
    at /home/ubuntu/workspace/node_modules/eslint/lib/config/config-file.js:388:36
    at Array.reduceRight (native)
```
So I checked this [similar issue](https://github.com/sindresorhus/xo/issues/92) and I tried to:

* update npm
* set `root: true` in eslint config, according to this [referenced issue](https://github.com/eslint/eslint/issues/5721)
* check versions of xo and eslint, they were fine

With no success. So the only difference that I found, is that when I first installed xo, I used the command

```bash
xo --init
```

That sounds weird for me, but I tried anyway, and after running that command I could run xo again, so it fix it. BUT, that erased all my xo config in my package.json, so I think it might be an issue.

**Comment by jamestalmage** [comment] 2016-04-22 23:24
@YerkoPalma - Is this a reproducible issue? Or just happened once?

If you can provide steps necessary to reproduce, that would help us troubleshoot the issue.

I have never played with cloud9. So, step-by-step reproduction instructions would help a lot.

**Comment by jfmengels** [comment] 2016-04-23 11:56
It's definitely reproducible, though I have no idea how. The same error has broken all my builds on https://github.com/jfmengels/eslint-plugin-lodash-fp, though only on Node v4 (works in 0.1X and v5).
https://travis-ci.org/jfmengels/eslint-plugin-lodash-fp/jobs/125133818

I seem to be able to reproduce it locally when I use Node v4, run `rm -r node_modules && npm i` then run xo (or in my case `npm test`). So if you want to reproduce it, you can clone my repo and repeat those steps.

**Comment by YerkoPalma** [comment] 2016-04-25 00:16
It seems that the `xo --init` command install some dependencies that aren't loaded when simply `npm install` is run. I just saw that when the init command is executed the [`xo-init`](https://github.com/sindresorhus/xo-init) package is loaded.

**Comment by sindresorhus** [comment] 2016-04-25 06:53
[`xo-init` only installs XO as a devDependency](https://github.com/sindresorhus/xo-init/blob/c72c1468a5a7f3188664e4f84c3568cfe6be31fe/index.js#L106), so I don't really understand what you're referring to.

**Comment by YerkoPalma** [comment] 2016-04-25 13:15
Sorry, I'm mixing topics here. Let me explain again.

First of all, the steps to reproduce are very simple:

1. Globally install xo
2. Pick some project and add xo to it through the `xo --init` command
3. Clone that repo to a new local folder
4. `npm install`
5. Run `npm test` and watch the error.

Now, I mentioned the `xo-init` package, because a workaround for that error for me was, after the step 5 of the previous list run.

6. `xo --init` 
7. Re add the `"xo"` entry on `package.json`

The last step on the workaround is because xo-init erase that from the package.json. I guess that is in [this line](https://github.com/sindresorhus/xo-init/blob/c72c1468a5a7f3188664e4f84c3568cfe6be31fe/index.js#L83)

**Comment by jamestalmage** [comment] 2016-04-25 19:33
https://docs.c9.io/docs/writing-a-nodejs-app

> Cloud9 IDE was built on top of the Node.js platform, and as such, you have full access to the node runtime. Currently, we support running versions **v0.6.x, v0.8.x, and v0.10.x.**

I hope those docs are out of date, because that is almost certainly your problem otherwise.

**Comment by YerkoPalma** [comment] 2016-04-25 19:50
My node version is `v4.4.0`. Just as @jfmengels. I think that if it is some problem with node version, the first run wouldn't have worked or the workaround with xo --init

**Comment by jamestalmage** [comment] 2016-04-25 20:21
OK, I just verified using @jfmengels example. (@YerkoPalma - please provide repo links in the future, it makes it way easier to figure out what you are talking about).

This is a dependency resolution issue. It's not related to config. And it appears to be internal to eslint.

I have no idea why it only happens on Node 4. That's just weird. 

I don't understand why [`pluin.load`](https://github.com/eslint/eslint/blob/master/lib/config/plugins.js#L106) does not use [`module-resolver`](https://github.com/eslint/eslint/blob/master/lib/util/module-resolver.js). Maybe that would fix things.

**Comment by YerkoPalma** [comment] 2016-04-25 20:24
I think it's also weird that `xo --init` fix the issue if it just add `xo` as a dev dependency

**Comment by jamestalmage** [comment] 2016-04-25 21:09
OK, weirdness:

Using `npm install` on Node 4 in Jeffs repo:

# Tested Results

## Node 0.12 - npm@2.5.1

Status: Works

Directory Layout:

```
/node_modules
  /eslint
  /xo
    /node_modules
       eslint          (not deduped)
       eslint-plugin-XXX 
```


## Node 4.4.0 - npm@2.14.2

Status: Failure.

Directory Layout:

```
/node_modules
  /eslint
  /xo
    /node_modules
       ... eslint is not here? Why is npm@2 doing a partial dedupe like this? Is this expected?
       eslint-plugin-XXX 
```

You can see why eslint can't resolve the plugin. It has no idea it needs to look inside `xo/node_modules`.

Removing `eslint` as both a peerDependency and devDependency, it all works.


## Node 5 - np@3

Status: works

Directory layout:

```
/node_modules
  /eslint
  /xo
  /eslint-plugin-XXX
```

eslint has no problem resolving the plugin - everything is flat


# Solutions

## Solution 1

Upgrade to `npm@3`

`eslint-plugin-ava` does not have these failures on Travis, because it upgrades to npm@3 in `.travis.yml`:

```yaml
before_install:
  - npm i -g npm
```

## Solution 2

Downgrade to an older `npm@2` that will not dedupe at all. I have confirmed `npm@2.5` works.

## Solution 3

Remove `eslint` as a `devDependency` and `peerDependency`. If you are using XO, it will already install `eslint` for you. Unless you are developing an eslint plugin, you shouldn't need it as a dependency.

**Comment by sindresorhus** [comment] 2016-04-30 18:13
I've seen this before too. Had to upgrade npm for Node.js 4 here: https://github.com/sindresorhus/eslint-plugin-xo/blob/acf538efc87ffdfbf2ba24f247b19fd45ad568e4/.travis.yml#L9 I'd argue this is an ESLint bug and should be reported there.

> I don't understand why pluin.load does not use module-resolver. Maybe that would fix things.

@jamestalmage Can you open an issue on ESLint?

**Comment by sindresorhus** [comment] 2016-10-09 16:40
Closing as it's looks like it's an ESLint bug and should be opened there.

**Closed by sindresorhus** 2016-10-09 16:40 UTC
Labels: bug
